'use client';
import {useEffect,useState} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import venues from '@/lib/venues.json';
type Paper={title:string;venue:string;year:number;url:string;category:string;first_seen:string;publication_type?:string;verification?:string};
export default function Home(){
const [scope,setScope]=useState('render');
const [kind,setKind]=useState('all');
const [papers,setPapers]=useState<Paper[]>([]),[query,setQuery]=useState(''),[venue,setVenue]=useState('全部'),[status,setStatus]=useState('正在读取论文库…');
useEffect(()=>{fetch('/api/papers').then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{papers:Paper[];message:string}>}).then(d=>{setPapers(d.papers);setStatus(d.message)}).catch(()=>setStatus('暂时无法读取论文库，请稍后刷新。'))},[]);
const result=papers.filter(p=>(venue==='全部'||p.venue===venue)&&(kind==='all'||(venues.journal.includes(p.venue)?'journal':'conference')===kind)&&p.title.toLowerCase().includes(query.toLowerCase())&&(scope==='all'||p.category==='渲染加速候选')&&!/belief propagation|\bSLAM\b|active mapping|registration|human representation/i.test(p.title)).sort((a,b)=>b.year-a.year||b.first_seen.localeCompare(a.first_seen));
return <main><header><strong>GS / OBSERVATORY</strong><span>3D Gaussian Splatting · Research radar</span></header><section className="intro"><small>论文观察站 / RENDERING SYSTEMS</small><h1>更快的渲染，<br/>值得追踪的研究。</h1><p>聚焦 3DGS 渲染加速。覆盖 AI 顶会与精选高水平期刊，区分渲染、训练与压缩。</p></section><section><div className="toolbar"><Input aria-label="搜索论文标题" placeholder="搜索论文标题、方法名称…" value={query} onChange={e=>setQuery(e.target.value)}/><span>{result.length} 篇论文</span></div><div className="toolbar"><Button variant={scope==='render'?'default':'outline'} onClick={()=>setScope('render')}>渲染加速</Button><Button variant={scope==='all'?'default':'outline'} onClick={()=>setScope('all')}>含训练与压缩相关方向</Button></div><div className="toolbar"><label>出版类型 <select aria-label="出版类型" value={kind} onChange={e=>{setKind(e.target.value);setVenue('全部')}}><option value="all">会议与期刊</option><option value="conference">会议</option><option value="journal">期刊</option></select></label></div><nav aria-label="会议与期刊筛选">{['全部',...venues.conference,...venues.journal].map(v=><Button key={v} variant={venue===v?'default':'outline'} onClick={()=>setVenue(v)}>{v}</Button>)}</nav><p className="status" role="status">{status}</p>{result.map((p,i)=><article key={p.url}><span>{String(i+1).padStart(2,'0')}</span><div><small>{venues.journal.includes(p.venue)?'期刊':'会议'} · {p.venue} {p.year} / {p.category}</small><h2><a href={p.url} target="_blank" rel="noreferrer">{p.title} ↗</a></h2><p>首次收录 {p.first_seen.slice(0,10)} · {p.verification || '正式论文记录'}</p></div></article>)}{!result.length&&<p className="empty">暂无匹配论文。可以调整关键词或会议筛选。</p>}</section><footer>精选 AI、视觉、图形学主会与期刊 · 排除 workshop 和未核实预印本 · 方向标签为规则筛选候选，阅读原文确认实际渲染收益。</footer></main>
}
